spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置数据库连接相关属性
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8
    username: root
    password: "080418"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.xzit.model
  mapper-locations: classpath:mapper/*.xml
