spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8
          username: root
          password: "080418"
        slave:
          url: jdbc:mysql://localhost:3306/db2?serverTimezone=GMT%2B8
          username: root
          password: "080418"
mybatis-plus:
  type-enums-package: com.xzit.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
